### ISSUE TITLE
Add support for stat tracking

### ISSUE THREAD

**Issue by Morgul** [SkewedAspect/card-crimes#4]
We want to track stats on a per user basis:

- [ ] Games Won
- [ ] Total Points
- [ ] Average Points per game
- [ ] Most frequently won black card (a threshold of 3 wins)
- [ ] Most frequent winning white card (a threshold of 3 wins)

This depends on #3.
